# Generated by Django 4.2.1 on 2023-06-01 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_treat'),
    ]

    operations = [
        migrations.AddField(
            model_name='dog',
            name='treats',
            field=models.ManyToManyField(to='main_app.treat'),
        ),
    ]
